import Vue from 'vue'
import { NavBar, Form, Field, Button, Toast, Tabbar, TabbarItem, Icon, Image as VanImage, Grid, GridItem, Cell, CellGroup } from 'vant';
import { Dialog } from 'vant';
import { Popup } from 'vant';
import { DatetimePicker } from 'vant';
import { Uploader } from 'vant';
import { Tab, Tabs } from 'vant';
import { List } from 'vant';
import { PullRefresh } from 'vant';
import { Divider } from 'vant';
import { ActionSheet } from 'vant';
import { Search } from 'vant';

Vue.use(Search);
Vue.use(ActionSheet);
Vue.use(Divider);
Vue.use(PullRefresh);
Vue.use(List);
Vue.use(NavBar);
Vue.use(Form);
Vue.use(Field);
Vue.use(Button);
Vue.use(Toast);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Icon);
Vue.use(VanImage);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Dialog);
Vue.use(Popup);
Vue.use(DatetimePicker);
Vue.use(Uploader);
Vue.use(Tab);
Vue.use(Tabs);